### PR TITLE
updating android studio 2.2 and com.android.tools.build:gradle to 2.2.0

### PR DESCRIPTION
**Pull request by wendersonferreira**

### CODE REVIEW

**Comment by wendersonferreira** [comment]
i'm sorry, I will correct messages lint

**Comment by friederbluemle** [comment]
@wendersonferreira Hey, I cherry-picked cef4586fc1c0a774fc368af548ede481b103fcbd onto my branch in #32 and solved the Lint errors in a slightly different way. Can you check please?

**Comment by wendersonferreira** [comment]
Thanks! I will do this now, @friederbluemle

**Comment by Michenux** [comment]
Can you tell me if i have to accept this pull request or the #32 ? or both ?

**Comment by friederbluemle** [comment]
@Michenux As stated in #32 - I cherry-picked one of the commits from @wendersonferreira, so #32 fully supersedes #31 (which can be closed once #32 is merged).

**Pull request closed without merging**
